// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TakeGYM.Services.AppDbContext;

namespace TakeGYM.Migrations
{
    [DbContext(typeof(TakeGYMContext))]
    [Migration("20220624145422_RemoveMinLenghtCPFTeacher")]
    partial class RemoveMinLenghtCPFTeacher
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TakeGYM.Models.Exercise.Exercise", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BodyRegion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercise");
                });

            modelBuilder.Entity("TakeGYM.Models.ExerciseTrainingSheet.ExerciseTraningsheet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExerciseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NumbersIteration")
                        .HasColumnType("int");

                    b.Property<int>("NumbersOfSet")
                        .HasColumnType("int");

                    b.Property<string>("TrainingsheetId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TrainingsheetId");

                    b.ToTable("Exercise_Trainingsheet");
                });

            modelBuilder.Entity("TakeGYM.Models.PersonalAlert.PersonalAlert", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PersonalID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StudentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrainingSheetObjective")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonalID");

                    b.HasIndex("StudentID");

                    b.ToTable("Alert");
                });

            modelBuilder.Entity("TakeGYM.Models.Structures.Schedule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeacherId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("TakeGYM.Models.Student.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CEP")
                        .HasColumnType("nvarchar(9)")
                        .HasMaxLength(9);

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasPersonal")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalScheduleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PersonalScheduleId");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasFilter("[Phone] IS NOT NULL");

                    b.HasIndex("TeacherID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("TakeGYM.Models.Teacher.Teacher", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPersonal")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasFilter("[Phone] IS NOT NULL");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("TakeGYM.Models.TrainingSheet.TrainingSheet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PersonalID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrainingSheetObjective")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonalID");

                    b.HasIndex("StudentID");

                    b.ToTable("TrainingSheet");
                });

            modelBuilder.Entity("TakeGYM.Models.ExerciseTrainingSheet.ExerciseTraningsheet", b =>
                {
                    b.HasOne("TakeGYM.Models.TrainingSheet.TrainingSheet", "Trainingsheet")
                        .WithMany("Exercises")
                        .HasForeignKey("ExerciseId");

                    b.HasOne("TakeGYM.Models.Exercise.Exercise", "Exercise")
                        .WithMany("TrainingSheets")
                        .HasForeignKey("TrainingsheetId");
                });

            modelBuilder.Entity("TakeGYM.Models.PersonalAlert.PersonalAlert", b =>
                {
                    b.HasOne("TakeGYM.Models.Teacher.Teacher", "Personal")
                        .WithMany("Alerts")
                        .HasForeignKey("PersonalID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TakeGYM.Models.Student.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID");
                });

            modelBuilder.Entity("TakeGYM.Models.Structures.Schedule", b =>
                {
                    b.HasOne("TakeGYM.Models.Teacher.Teacher", null)
                        .WithMany("WorkSchedules")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("TakeGYM.Models.Student.Student", b =>
                {
                    b.HasOne("TakeGYM.Models.Structures.Schedule", "PersonalSchedule")
                        .WithMany()
                        .HasForeignKey("PersonalScheduleId");

                    b.HasOne("TakeGYM.Models.Teacher.Teacher", "Teacher")
                        .WithMany("Students")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("TakeGYM.Models.TrainingSheet.TrainingSheet", b =>
                {
                    b.HasOne("TakeGYM.Models.Teacher.Teacher", "Personal")
                        .WithMany()
                        .HasForeignKey("PersonalID");

                    b.HasOne("TakeGYM.Models.Student.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID");
                });
#pragma warning restore 612, 618
        }
    }
}
